In [6]:
# Dependencies and Setup
import matplotlib.pyplot as plt
import pandas as pd
import scipy.stats as st
import numpy as np

# Study data files
mouse_metadata_path = "data/Mouse_metadata.csv"
study_results_path = "data/Study_results.csv"

# Read the mouse data and the study results
mouse_metadata = pd.read_csv(mouse_metadata_path)
study_results = pd.read_csv(study_results_path)

# Combine the data into a single dataset
mouse_studies = pd.merge(study_results, mouse_metadata,how='outer', on="Mouse ID")


# Display the data table for preview
mouse_studies.head()

,Mouse ID,Timepoint,Tumor Volume (mm3),Metastatic Sites,Drug Regimen,Sex,Age_months,Weight (g)
0,b128,0,45.000000,0,Capomulin,Female,9,22
1,b128,5,45.651331,0,Capomulin,Female,9,22
2,b128,10,43.270852,0,Capomulin,Female,9,22
3,b128,15,43.784893,0,Capomulin,Female,9,22
4,b128,20,42.731552,0,Capomulin,Female,9,22

In [7]:
# Checking the number of mice.
mice_count = mouse_studies['Mouse ID'].count()
mice_count

1893

In [8]:
mouse_df = pd.DataFrame(mouse_studies)
mouse_df

,Mouse ID,Timepoint,Tumor Volume (mm3),Metastatic Sites,Drug Regimen,Sex,Age_months,Weight (g)
0,b128,0,45.000000,0,Capomulin,Female,9,22
1,b128,5,45.651331,0,Capomulin,Female,9,22
2,b128,10,43.270852,0,Capomulin,Female,9,22
3,b128,15,43.784893,0,Capomulin,Female,9,22
4,b128,20,42.731552,0,Capomulin,Female,9,22
...,...,...,...,...,...,...,...,...
1888,m601,25,33.118756,1,Capomulin,Male,22,17
1889,m601,30,31.758275,1,Capomulin,Male,22,17
1890,m601,35,30.834357,1,Capomulin,Male,22,17
1891,m601,40,31.378045,1,Capomulin,Male,22,17
1892,m601,45,28.430964,1,Capomulin,Male,22,17

In [22]:
# Getting the duplicate mice by ID number that shows up for Mouse ID and Timepoint.
timepoint = mouse_df['Timepoint']
mouse_id = mouse_df['Mouse ID']

dup =[]
   
for mouse_id in timepoint: 

    dup.append[mouse_id][timepoint]


print(dup)

TypeError: 'builtin_function_or_method' object is not subscriptable

In [10]:
mouse_group = mouse_df.groupby(["Drug Regimen"])

mouse_group.describe()

             Timepoint                                                     \
                 count       mean        std  min   25%   50%   75%   max
Drug Regimen
Capomulin        230.0  21.565217  14.384994  0.0  10.0  20.0  35.0  45.0
Ceftamin         178.0  19.747191  14.283969  0.0   5.0  20.0  30.0  45.0
Infubinol        178.0  18.174157  13.473473  0.0   5.0  15.0  30.0  45.0
Ketapril         188.0  19.707447  14.029935  0.0   5.0  20.0  30.0  45.0
Naftisol         186.0  19.623656  14.184814  0.0   5.0  20.0  30.0  45.0
Placebo          181.0  18.674033  13.890798  0.0   5.0  15.0  30.0  45.0
Propriva         161.0  16.863354  13.472424  0.0   5.0  15.0  25.0  45.0
Ramicane         228.0  21.425439  14.275720  0.0  10.0  20.0  35.0  45.0
Stelasyn         181.0  19.226519  13.842710  0.0   5.0  20.0  30.0  45.0
Zoniferol        182.0  19.368132  14.384679  0.0   5.0  15.0  30.0  45.0

             Tumor Volume (mm3)             ... Age_months       Weight (g)  \
                          count       mean  ...        75%   max      count
Drug Regimen                                ...
Capomulin                 230.0  40.675741  ...       20.0  24.0      230.0
Ceftamin                  178.0  52.591172  ...       20.0  24.0      178.0
Infubinol                 178.0  52.884795  ...       23.0  24.0      178.0
Ketapril                  188.0  55.235638  ...       19.0  24.0      188.0
Naftisol                  186.0  54.331565  ...       19.0  23.0      186.0
Placebo                   181.0  54.033581  ...       17.0  21.0      181.0
Propriva                  161.0  52.322552  ...       21.0  24.0      161.0
Ramicane                  228.0  40.216745  ...       18.0  23.0      228.0
Stelasyn                  181.0  54.233149  ...       21.0  23.0      181.0
Zoniferol                 182.0  53.236507  ...       16.0  24.0      182.0


                   mean       std   min   25%   50%   75%   max
Drug Regimen
Capomulin     19.965217  2.732404  15.0  17.0  20.5  22.0  25.0
Ceftamin      27.398876  1.581460  25.0  26.0  28.0  28.0  30.0
Infubinol     27.196629  2.183810  23.0  25.0  27.0  29.0  30.0
Ketapril      27.861702  1.841884  25.0  26.0  28.0  30.0  30.0
Naftisol      27.166667  1.499249  25.0  26.0  27.0  28.0  30.0
Placebo       27.928177  1.837973  25.0  27.0  28.0  30.0  30.0
Propriva      27.043478  1.670882  25.0  26.0  26.0  29.0  30.0
Ramicane      19.679825  3.235014  16.0  17.0  19.0  22.0  25.0
Stelasyn      27.856354  1.643616  25.0  27.0  28.0  29.0  30.0
Zoniferol     27.692308  1.419612  25.0  27.0  28.0  29.0  30.0

[10 rows x 40 columns]