In [1]:
import pandas as pd
import numpy as np

In [9]:
from citipy import citipy
import gmaps
from config import gkey
import pandas as pd
import requests
import random
import json
import matplotlib.pyplot as plt

In [10]:
weather_csv = 'Resources/weather_data.csv'

weather_df = pd.read_csv(weather_csv)

weather_df

,Unnamed: 0,city_name,country,lat,humidity,temp,cloudiness,wind_speed
0,0,Husavik,IS,66.04,92,-3.98,89,1.00
1,1,Ushuaia,AR,-54.80,43,9.30,75,2.60
2,2,Jamestown,US,42.10,93,10.31,90,7.70
3,3,Bonthe,SL,7.53,88,29.33,100,2.94
4,4,Olhão,PT,37.03,93,18.50,75,2.60
...,...,...,...,...,...,...,...,...
495,495,Aulla,IT,44.21,83,13.15,20,1.65
496,496,Menzel Salem,TN,35.86,29,14.23,0,4.10
497,497,Moguer,ES,37.28,85,16.30,87,1.34
498,498,Casteltermini,IT,37.54,82,15.97,1,0.61
499,499,Yendi,GH,9.44,57,30.08,50,0.68

In [11]:
dropna_weather_df = weather_df.dropna()
del dropna_weather_df["Unnamed: 0"]
dropna_weather_df.head(20)

          city_name country    lat  humidity   temp  cloudiness  wind_speed
0           Husavik      IS  66.04        92  -3.98          89        1.00
1           Ushuaia      AR -54.80        43   9.30          75        2.60
2         Jamestown      US  42.10        93  10.31          90        7.70
3            Bonthe      SL   7.53        88  29.33         100        2.94
4             Olhão      PT  37.03        93  18.50          75        2.60
5       Port-Gentil      GA  -0.72        83  27.86          63        4.74
6          Saldanha      ZA -33.01        82   9.83           0        4.60
7               Bud      US  39.45        82  15.45          90        1.50
8    Ribeira Grande      PT  38.52        59  15.29          75        2.10
9            Dingle      PH  11.00        90  27.76         100        2.86
10     Uusikaupunki      FI  60.80        93   7.94          90        2.60
11     Kruisfontein      ZA -34.00        76  13.55           0        0.45
12       Virovitica      HR  45.83        83   6.03          95        4.76
13         Hermanus      ZA -34.42        91   9.17           0        2.72
14            Ardea      IT  41.61        87  14.18           5        1.00
15      George Town      MY   5.41        88  30.71          40        1.50
16        Cape Town      ZA -33.93        82   9.75           0        7.20
17  Arraial do Cabo      BR -22.97        74  24.44          20        8.20
19       Middelburg      ZA -25.78        57  14.80           0        4.13
20         Olafsvik      IS  64.89        93  -5.50         100       12.35

In [15]:
gmaps.configure(api_key=gkey)

# Locations
locations = dropna_weather_df[["city_name", "country"]]

humidity = dropna_weather_df["humidity"].astype(float)

In [19]:
fig = gmaps.figure()

# Create heat layer
heat_layer = gmaps.heatmap_layer(locations, weights=humidity, 
                                 dissipating=False, max_intensity=100,
                                 point_radius=2)
fig.add_layer(heat_layer)

fig

if TraitError:
    print("did not capture the correct data when creating the CSV.")

TraitError: Husavik is not a valid latitude. Latitudes must be floats

In [23]:
vacation_no_cloud = dropna_weather_df[dropna_weather_df["cloudiness"] == 0]
# Filter vacation with max temp above 21
vacation_temp_min = vacation_no_cloud[vacation_no_cloud["temp"] > 21]
# Filter vacation with max temp below 26
vacation_temp_max = vacation_temp_min[vacation_temp_min["temp"] < 26]
# Filter vacation with wind speed below 10 mph
vacation_wind = vacation_temp_max[vacation_temp_max["wind_speed"] < 10]
# Filter vacation with humidity below 60 %
perfect_vacation = vacation_wind[vacation_wind["humidity"] < 60]
# Set Index
indexed_vacation = perfect_vacation.reset_index()
del indexed_vacation["index"]
indexed_vacation

       city_name country    lat  humidity   temp  cloudiness  wind_speed
0         Assiut      EG  27.18        39  25.98           0        4.10
1           Kang      BW -23.68        21  21.48           0        7.64
2       Tessalit      ML  20.20        14  25.96           0        3.21
3   Marsá Maţrūḩ      EG  31.35        56  22.71           0        2.10
4   Umm Kaddadah      SD  13.60        12  25.11           0        5.95
5          Birao      CF  10.28        46  24.67           0        2.18
6          Bilma      NE  18.69        14  23.85           0        2.38
7          Gweta      BW -20.18        37  21.90           0        9.10
8          Ţahţā      EG  26.77        28  25.53           0        4.60
9          Kafue      ZM -15.77        27  21.18           0        2.10
10        Lukulu      ZM -14.37        31  21.36           0        2.41
11       Biltine      TD  14.53        13  24.87           0        4.95
12         Gusau      NG  12.16        21  25.02           0        2.03
13       Tsabong      BW -26.02        20  22.46           0        8.10
14        Kasane      BW -17.82        22  21.80           0        2.72

In [24]:
len(indexed_vacation)

15